from Handlers.general import register_handlers_general
from Handlers.fsm_quiz import register_handlers_fsmquiz
from Handlers.FTS_Scrape import register_handlers_fts_parsing
import Handlers.FTS_Parser
import Handlers.parsing_dicts
